### ISSUE TITLE
Reporte de la práctica 8

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-mad#1]
[Actividad 8 práctica de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-mad/files/15125380/Actividad.8.practica.de.Hilos.pdf)

Integrantes:
Marlene Maricela Osorio Ramírez
Adriana Hernández Martínez
Daniel Velasco López

**Comment by Ariadnamonserrat10** [comment]
20 de 20 Cumple claramente con lo mencionado dentro de la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
